package com.example.demo.exception;

public enum ExceptionMessageEnum {
    JOB_NOT_FOUND("JOB NO ENCONTRADO"), JOB_IS_EMPTY("DATOS DE JOB INCOMPLETOS"),
    USER_NOT_FOUND("USER NO ENCONTRADO"),USER_IS_EMPTY("DATOS DE USER INCOMPLETOS"),
    JOB_OFFER_NOT_FOUND("JOB_OFFER NOT FOUND"),JOB_OFFER_IS_EMPTY("DATOS DE JOB OFFER INCOMPLETOS"),
    EMAIL_REPEATED("EMAIL YA REGISTRADO, INGRESE OTRO EMAIL"),FORMAT_EMAIL_INCORRECT("FORMATO DE EMAIL INCORRECTO"),
    NOT_SECURE_PASSWORD("lA CONTRASEÑA DEBE TENER MAS DE 8 CARACTERES, AL MENOS 1 MAYUSCULA Y AL MENOS UN NÚMERO"),
    EMAIL_NOT_FOUND("EMAIL NO ENCONTRADO"),PASSWORD_INCORRECT("CONTRASEÑA INCORRECTA");

    private final String message;
    ExceptionMessageEnum(String message){
        this.message=message;
    }
    public String getMessage(){
        return message;
    }

}
